# Enables modern AndroidX libraries
android.useAndroidX=true

# Optimizes the build speed and gives the GitHub Actions runner enough memory
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Enforces strict Kotlin code styling
kotlin.code.style=official
